AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
Style/FrozenStringLiteralComment:
  Enabled: true
Style/StringLiterals:
  Enabled: true

Layout/LineLength:
  Max: 100
  Exclude:
    - exe/**
    - bin/**
    - Gemfile
    - sapi-client.gemspec
    - test/**/*

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - lib/tasks/*
    - sapi-client-ruby.gemspec

Metrics/ClassLength:
  Exclude:
    - test/**/*

Style/Documentation:
  Exclude:
    - test/**/*

Style/OpenStructUse:
  Enabled: false
