AllCops:
  TargetRubyVersion: 2.5
Style/FrozenStringLiteralComment:
  Enabled: true
Style/StringLiterals:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - bin/**
    - Gemfile
    - sapi-client.gemspec
    - test/**/*

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - test/**/*
    - lib/tasks/*

Metrics/ClassLength:
  Exclude:
    - test/**/*
