name: Release and Publish Gem
on:
  release:
    types: [published]

jobs:
  build:
    name: "Build gem package"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "Publish gem"
        run: "make publish"