name: Ruby tests

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        ruby: ['3.3', '3.4']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Rubocop
      run: bundle exec rubocop
    - name: Run tests
      run: bundle exec rake test
